# data set path
filtered_data_path: '/data/zfr888/EMD_4603/data_emd4603/data.h5' # extracted data point set
data_path: '/data/zfr888/EMD_4603/data_emd4603/original' # original data set

# stored path
saving_path: '/data/zfr888/EMD_4603/Results/'
algorithm_name: 'gmmu_cavi_llh_hist'
filtered_particle_saving_path: '/data/zfr888/EMD_4603/Results/filtered_particle' #'/local/scratch/v_yijian_bai/disca/deepcluster_gmmu/results/hist'

# setting of YOPO and GMMU
image_size: 24    # subtomogram size
input_size: 24
# candidateKs: [10,11,12,13,14,15,16]   # candidate number of clusters to test
candidateKs: [7,8,9,10,11]   # candidate number of clusters to test


batch_size: 2
scanning_num: 1 # the number of scanning
factor: 2 # the num of scanning division
M: 10   # number of DISCA training iterations
lr: 0.01   # CNN learning rate
loss_function: 'categorical_crossentropy' # loss function used in TF
optimizer: 'adam'
hidden_num: 32

reg_covar: 0.000001 # for inversing the variance matrix and initialization (adding on the diagonal)
u_filter_rate: 0.025 # the higher, the more data will be classified as outliers
alpha: 1.0 # the higher, the more cluters will be generated

scanning_bottom: 100
scanning_upper: 20000

# visualization

num_labels: 10
DIVIDE: 40

sub_epoch: 100
subtomo_num: 7000
subtomo_num_test: 1000